### ISSUE TITLE
Incompatible with IntelliJ IDEA 2020.2

### ISSUE THREAD

**Issue by JasonHK** [FalseHonesty/intellij-preprocessor#1]
IntelliJ IDEA 2020.2 has reported that this plugin is incompatible with it. Here's the error message:

```
Plugin Error: Plugin "Preprocessor Support" is incompatible (until build 201.SNAPSHOT < IC-202.6397.94).
```

**Comment by FalseHonesty** [comment]
Ah my bad, forgot I had to keep version support updated. Let me see if I can get a new build out, thanks!

**Comment by FalseHonesty** [comment]
Alright, I've submitted a new build to the IntelliJ plugin market, it should be available for downloading in 1-2 days :)
